# Generated by Django 5.1 on 2025-01-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_balance_user_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_stripe_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
