# Generated by Django 5.1 on 2025-01-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_account_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
    ]
